name: Build and Push Docker Image

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'workflow_dispatch' # Ensure a tag is present and manually triggered
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract tag version
      id: extract_tag
      run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/netcup-dyndns:latest
          ghcr.io/${{ github.repository_owner }}/netcup-dyndns:${{ env.TAG_VERSION }}
