name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract tag version
      id: extract_tag
      run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/netcup-dyndns:latest
          ghcr.io/${{ github.repository_owner }}/netcup-dyndns:${{ env.TAG_VERSION }}
        labels: |
          org.opencontainers.image.version=${{ env.TAG_VERSION }}
